In [1]:
import pandas as pd
import json

In [2]:
from backend.services.stratz import match_data

In [30]:
data = match_data(8244847494)

In [32]:
data = data['data']['match']

In [34]:
df = pd.json_normalize(data, max_level=3)

In [6]:
df

,actualRank,averageImp,averageRank,analysisOutcome,bracket,bottomLaneOutcome,barracksStatusDire,barracksStatusRadiant,clusterId,direKills,...,towerStatus,towerDeaths,winRates,laneReport.radiant,laneReport.dire,playbackData.buildingEvents,playbackData.runeEvents,playbackData.roshanEvents,playbackData.towerDeathEvents,playbackData.wardEvents
0,64,-11,None,NONE,6,TIE,2,63,272,"[0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 2, 1, 0, ...",...,"[{'outposts': [{'isRadiantSide': True, 'isCont...","[{'attacker': None, 'isRadiant': True, 'npcId'...","[0.5, 0.5, 0.5, 0.49, 0.42, 0.42, 0.39, 0.47, ...","[{'midLane': {'denyCount': 3, 'meleeCount': 2,...","[{'midLane': {'denyCount': 0, 'meleeCount': 1,...","[{'didShrineActivate': None, 'hp': 1800, 'inde...","[{'action': 0, 'indexId': 791, 'location': 0, ...","[{'x': 150, 'y': 104}, {'x': None, 'y': None},...","[{'radiant': 4, 'dire': 0}, {'radiant': 4, 'di...","[{'action': 'SPAWN', 'fromPlayer': 1, 'indexId..."

In [7]:
df.shape

(1, 39)

In [8]:
data.keys()

dict_keys(['actualRank', 'averageImp', 'averageRank', 'analysisOutcome', 'bracket', 'bottomLaneOutcome', 'barracksStatusDire', 'barracksStatusRadiant', 'clusterId', 'direKills', 'didRadiantWin', 'durationSeconds', 'endDateTime', 'firstBloodTime', 'gameMode', 'isStats', 'laneReport', 'lobbyType', 'midLaneOutcome', 'numHumanPlayers', 'players', 'pickBans', 'playbackData', 'rank', 'regionId', 'replaySalt', 'radiantKills', 'radiantNetworthLeads', 'radiantExperienceLeads', 'sequenceNum', 'topLaneOutcome', 'towerStatus', 'towerDeaths', 'winRates'])

In [21]:
pd.json_normalize(data['laneReport'], 'radiant')

,midLane.denyCount,midLane.meleeCount,midLane.neutralCount,midLane.rangeCount,midLane.siegeCount,offLane.denyCount,offLane.meleeCount,offLane.neutralCount,offLane.siegeCount,safeLane.denyCount,safeLane.meleeCount,safeLane.neutralCount,safeLane.siegeCount
0,3,2,0,1,0,0,0,0,0,0,2,0,0
1,0,1,0,1,0,0,0,0,0,0,2,0,0
2,1,1,0,1,0,0,0,0,0,1,1,0,0
3,1,2,0,1,0,0,0,0,0,0,0,0,0
4,0,2,0,0,0,1,1,0,0,1,3,2,0
5,0,1,0,0,0,0,1,0,0,0,3,0,0
6,0,2,0,0,0,0,0,0,0,1,3,2,0
7,0,0,0,1,0,0,3,0,0,0,0,2,0
8,1,3,0,0,0,1,2,1,0,0,0,1,0
9,0,1,0,1,0,3,2,0,0,0,0,6,0
10,0,1,0,0,0,0,1,0,0,0,0,0,0
11,1,3,0,1,0,0,0,0,0,0,0,10,0
12,0,3,0,2,0,3,3,0,0,0,0,3,0
13,0,3,0,1,1,0,3,0,0,0,0,3,0
14,0,0,6,0,0,1,2,0,1,0,1,2,0
15,1,5,0,2,0,0,2,0,0,0,0,6,0
16,1,0,0,0,0,1,1,0,0,0,1,3,0
17,0,3,0,2,0,1,2,0,0,0,0,0,0

In [24]:
pd.json_normalize(data['towerDeaths'])

   attacker  isRadiant  npcId  time
0      None       True     18   467
1      None      False     27   620
2      None      False     26   929
3      None      False     28  1103
4      None       True     17  1316
5      None      False     29  1567
6      None       True     21  1617
7      None      False     31  2200
8      None      False     30  2227
9      None      False     34  2478
10     None      False     32  2577
11     None      False     33  2733
12     None      False     35  2742
13     None      False     35  2748
14     None      False     37  2757
15     None      False     45  2758
16     None      False     49  2770
17     None      False     48  2779
18     None      False     37  2787
19     None      False     44  2790
20     None      False     46  2794
21     None      False     51  2807